#!/usr/bin/env perl
use strict;
use warnings;
use lib 'modules';

=head1 AUTHOR

Sendu Bala <sb10@sanger.ac.uk>.

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2011 Genome Research Limited.

This file is part of VRPipe.

VRPipe is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=cut

use VRPipe::LocalScheduler;

my $ls = VRPipe::LocalScheduler->new_with_options();

my ($command, @others) = @{$ls->extra_argv};
defined $command || die "No command specified\n";

$ls->start   if $command eq 'start';
$ls->status  if $command eq 'status';
$ls->restart if $command eq 'restart';
$ls->stop    if $command eq 'stop';

if ($command eq 'submit') {
    my $cmd = $others[0] || die "submit must be supplied a command to run\n";
    $ls->submit($cmd);
    exit;
}
elsif ($command eq 'jobs') {
    $ls->jobs(\@others);
    exit;
}
elsif ($command eq 'kill') {
    @others || die "kill must be supplied one or more ids\n";
    $ls->kill(\@others);
    exit;
}
elsif ($command eq 'process_queue') {
    $ls->process_queue;
    exit;
}
else {
    warn $ls->status_message, "\n";
    exit($ls->exit_code);
}