#!/usr/bin/env perl
use strict;
use warnings;

=head1 AUTHOR

Sendu Bala <sb10@sanger.ac.uk>.

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2011-2012 Genome Research Limited.

This file is part of VRPipe.

VRPipe is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=cut

use VRPipe::FrontEnd;

my $frontend = VRPipe::FrontEnd->new(
    description => "Dispatch work that needs to be done to the job scheduler (eg. LSF).",
    opt_spec    => [
        ['limit=i', q[Globally limit the number of submissions that will be dispatched], { default => 2000 }],
        ['verbose', 'Print lots of debugging information']
    ]
);
my $verbose = $frontend->opts('verbose');
my $limit   = $frontend->opts('limit');

my $manager = VRPipe::Manager->create(global_limit => $limit);
$manager->set_verbose_global(1) if $verbose;

while (1) {
    $manager->handle_submissions;
    print STDERR ". ";
    sleep(60);
}

exit;
