#!/usr/bin/env perl
use strict;
use warnings;
use lib '/my/vrpipe/checkout/modules';
use VRPipe::Persistent::SchemaBase;
VRPipe::Persistent::SchemaBase->database_deployment('testing');
use VRPipe::Persistent::Schema;

use Getopt::Long;
my $verbose = 0;
my $limit = 500;
my $result = GetOptions("verbose" => \$verbose, "limit=i" => \$limit);

my $manager = VRPipe::Manager->get(global_limit => $limit);
$manager->set_verbose_global(1) if $verbose;

while (1) {
    $manager->handle_submissions;
    print STDERR ". ";
    sleep(60);
}
print STDERR "\n";

exit;
