#!/usr/bin/env perl
use strict;
use warnings;

use VRPipe::Persistent::Schema;

use Getopt::Long;
my $verbose = 0;
my $limit = 2000;
my $result = GetOptions("verbose" => \$verbose, "limit=i" => \$limit);

my $manager = VRPipe::Manager->get(global_limit => $limit);
$manager->set_verbose_global(1) if $verbose;

while (1) {
    handle_pipeline();
    print STDERR ", ";
    sleep(60);
}

exit;

sub handle_pipeline {
    while (1) {
        last if $manager->trigger;
	print STDERR ". ";
        sleep(60);
    }
}
