#!/usr/bin/env perl
use strict;
use warnings;

=head1 AUTHOR

Sendu Bala <sb10@sanger.ac.uk>.

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2012 Genome Research Limited.

This file is part of VRPipe.

VRPipe is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=cut

use VRPipe::Interface::CmdLine;

my $cmdline = VRPipe::Interface::CmdLine->new(
    description => "See the overall state of active pipeline setups.",
    opt_spec    => [
        ['setup=s@',     'Only show details for the given PipelineSetup (by id or name); you can repeat this option', { persistent_object => 'PipelineSetup' }],
        ['incomplete|i', 'Only show details of PipelineSetups that are incomplete (does not affect --list mode)'],
        ['brief|b',      'Do not show full config details of each PipelineSetup, just the completion state summary'],
        ['list|l',       'Just list out the setup names and ids without details']
    ]
);

my $response = $cmdline->server_get('/status');
$cmdline->output($response);

exit;
