#!/usr/bin/env perl
use strict;
use warnings;

=head1 AUTHOR

Sendu Bala <sb10@sanger.ac.uk>.

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2011-2012 Genome Research Limited.

This file is part of VRPipe.

VRPipe is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=cut

use aliased 'VRPipe::Persistent::Schema' => 'PS';
use aliased 'DBIx::Class::DeploymentHandler' => 'DH';

my $s = PS->connect;

my $dh = DH->new({ schema => $s,
                   databases => PS->get_dbtype,
                   sql_translator_args => { add_drop_table => 0 },
                   script_directory => PS->get_schema_dir });

$dh->prepare_install;
$dh->install;

# Add table indexes from Persistent metadata
my $idx_cmds = PS->new->get_idx_sql('create');
if ($idx_cmds) {
	$s->storage->dbh_do(
		sub {
			my ($storage, $dbh, $idx_cmds) = @_;

			my ($cols,$txt_cols);
			foreach my $cmd (@{$idx_cmds}) {
			   $dbh->do($cmd);
			}
		},
		$idx_cmds
	);
}

exit;
