#!/usr/bin/env perl
use strict;
use warnings;
use lib 'modules';

use VRPipe::LocalScheduler;

my $ls = VRPipe::LocalScheduler->new_with_options();

my ($command, @others) = @{$ls->extra_argv};
defined $command || die "No command specified\n";

$ls->start   if $command eq 'start';
$ls->status  if $command eq 'status';
$ls->restart if $command eq 'restart';
$ls->stop    if $command eq 'stop';

if ($command eq 'submit') {
    my $cmd = $others[0] || die "submit must be supplied a command to run\n";
    $ls->submit($cmd);
    exit;
}
elsif ($command eq 'job') {
    my $id = $others[0] || die "job must be supplied an id\n";
    $ls->job($id);
    exit;
}
elsif ($command eq 'kill') {
    @others || die "kill must be supplied one or more ids\n";
    $ls->kill(@others);
    exit;
}
else {
    warn($ls->status_message);
    exit($ls->exit_code);
}